name: 'Build & Push Action'
description: 'Builds and pushes a Docker image'
inputs:
  projectName:
    description: 'Project Name'
    required: true
  imageName:
    description: 'Image Name'
    required: true
  imageVersion:
    description: 'Image Version'
    required: true
  dockerfilePath:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  registryUrl:
    description: 'Registry URL'
    required: true
  awsAccessKeyId:
    description: 'AWS Access Key Id'
    required: true
  awsSecretAccessKey:
    description: 'AWS Secret Access Key'
    required: true
  awsRegion:
    description: 'AWS Region'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.awsAccessKeyId }}
        aws-secret-access-key: ${{ inputs.awsSecretAccessKey }}
        aws-region: ${{ inputs.awsRegion }}
        
    - name: Docker login
      run: |
        aws ecr get-login-password --region ${{ inputs.awsRegion }} | docker login --username AWS --password-stdin ${{ inputs.registryUrl }}
      shell: bash

    - name: Build and push Docker image
      run: |
        docker build -t ${{ inputs.registryUrl }}/${{ inputs.projectName }}/${{ inputs.imageName }}:${{ inputs.imageVersion }} -f ${{ inputs.dockerfilePath }} .
        docker push ${{ inputs.registryUrl }}/${{ inputs.projectName }}/${{ inputs.imageName }}:${{ inputs.imageVersion }}
      shell: bash
